web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '${HOST}'

  environment:
    GITLAB_OMNIBUS_CONFIG: |
      # Add any other gitlab.rb configuration here, each on its own line
      external_url '${HOST}'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224

  ports:
    - '80:80'
    - '443:443'
    - '2224:22'

  volumes:
    - '${GITLAB_HOME}/config:/etc/gitlab'
    - '${GITLAB_HOME}/logs:/var/log/gitlab'
    - '${GITLAB_HOME}/data:/var/opt/gitlab'
gitlab_runner:
  image: 'gitlab/gitlab-runner:latest'
  restart: always
  volumes:
    - '/srv/gitlab-runner/config:/etc/gitlab-runner'
    - '/var/run/docker.sock:/var/run/docker.sock'
