stages:
  - build
  - deploy
  - test
  - push

build:
  script:
    - docker --version
    - docker build -t pyapp .
  stage: build
  tags:
    - localrunner
    - localshell

deploy:
  stage: deploy
  script:
    - docker rm --force pyappcontainer
    - docker run -d --name pyappcontainer -p 80:8080 pyapp
  tags:
    - localrunner
    - localshell

test:
  stage: test
  script:
    - curl localhost | grep Happy
  tags:
    - localrunner
    - localshell

push:
  stage: push
  script:
    - docker login -u $dockerhub_login -p $dockerhub_pass
    - docker tag pyapp:latest $dockerhub_login/pyapp:latest
    - docker push $dockerhub_login/pyapp:latest
  tags:
    - localrunner
    - localshell